@echo off
cd src
dir /b/s
@echo -
@echo ---------------------------------------------------------------------------------
@echo -
cd ..
cd resources
cd vista
dir /b/s
@echo -
@echo ---------------------------------------------------------------------------------
@echo -
cd ..
cd help
dir /b/s
cd ..
cd ..
