#= mi tema 2
# Basado en=vista.theme.themes.FlatPurpuraMisteriosoIJTheme

MenuBar.background=#2c2c3b
MenuBar.foreground=#d0d0d9
ToolBar.background=#2c2c3b
Button.foreground=#d0d0d9
Button.borderColor=#4e4c63
Button.focusedBorderColor=#814f9e
Button.default.background=#2c2c3b
Button.default.foreground=#d0d0d9
Visor.statusBarBackground=#000033
Visor.statusBarForeground=#ffffff
TextField.background=#3a384d
TextField.foreground=#d0d0d9
Component.accentColor=#a85ed6
Component.focusedBorderColor=#814f9e
TextArea.background=#3a384d
List.background=#2c2c3b
List.foreground=#d0d0d9
List.selectionBackground=#713a91
List.selectionForeground=#d0d0d9
List.selectionInactiveBackground=#3d3952
List.selectionInactiveForeground=#bbbbbb
Panel.background=#2c2c3b
Label.foreground=#d0d0d9
ComboBox.background=#3a384d
PasswordField.background=#3a384d
Spinner.background=#3a384d
Tree.selectionBackground=#713a91
Tree.selectionForeground=#d0d0d9
Table.selectionBackground=#713a91
Table.selectionForeground=#d0d0d9
TableHeader.background=#363445
Component.focusColor=#693687
JTextField.focusColor=#693687
ComboBox.focusColor=#693687
TabbedPane.focusColor=#693687
ScrollPane.focusColor=#693687
SplitPane.focusColor=#693687
Panel.focusColor=#693687
Component.borderColor=#4e4c63
TabbedPane.underlineColor=#9649cc
TabbedPane.contentAreaColor=#1a1721
TabbedPane.foreground=#d0d0d9
Separator.foreground=#4e4b61
Separator.color=#4e4b61
TitledBorder.titleColor=#bbbbbb
ProgressBar.foreground=#a85ed6
CheckBox.foreground=#d0d0d9
RadioButton.foreground=#d0d0d9
TitlePane.background=#2c2c3b
TextField.inactiveForeground=#646078
Label.disabledForeground=#646078
TextField.disabledBackground=#2c2c3b
